language: java

jdk:
  - openjdk8
  - oraclejdk11

install:
  - ./gradlew assemble -x signArchives -x uploadArchives

script:
  - ./gradlew check --debug --stacktrace --info

after_success:
  - ./gradlew jacocoTestReport coveralls
